title: L.O.V.E. Training
description: Leading, Organizing, Values, and Executing!
theme: just-the-docs

url: https://tanglewoodanalytics.com

aux_links:
  Source Code Repository: https://github.com/falserino/Leader